services:
  app:
    build:
      context: .  # Dùng Dockerfile trong thư mục hiện tại
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mydb:3306/springcommerce_db?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8081:8081"
    depends_on:
      - mydb
    networks:
      - spring_commerce-network

  mydb:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springcommerce_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - spring_commerce-network

volumes:
  uploads-data:
  db-data:

networks:
  spring_commerce-network:
    driver: bridge
